add ci publish

diff --git a/.github/workflows/publish.yaml b/.github/workflows/publish.yaml
--- a/.github/workflows/publish.yaml
+++ b/.github/workflows/publish.yaml
@@ -7,10 +7,25 @@ name: Publish to ghcr
 
 on:
   workflow_dispatch:
+    inputs:
+      version: 
+        type: string
+        description: "指定版本"
+        required: false
+      release: 
+        type: boolean
+        description: "推送"
+        required: false
+        default: false
+
+env:
+  APP: clash-exporter
 
 jobs:
   plan:
-    name: Plan 
+    name: Plan
+    outputs:
+      app: ${{ steps.options.outputs.app }}
     runs-on: ubuntu-latest
     steps:
       - name: Application Options
@@ -19,26 +34,36 @@ jobs:
         working-directory: .
         run: |
           PLATFORMS=$(\
-              docker buildx bake image-all --print --progress=quiet \
+              docker buildx bake image-all --print --progress=quiet -f docker-bake.hcl \
                   | jq --raw-output --compact-output '.target."image-all".platforms' \
           )
           SOURCE=$(\
-              docker buildx bake --list type=variables,format=json --progress=quiet \
+              docker buildx bake --list type=variables,format=json --progress=quiet -f docker-bake.hcl \
                   | jq --raw-output '.[] | select(.name == "SOURCE") | .value' \
           )
-          VERSION=$(\
-              docker buildx bake --list type=variables,format=json --progress=quiet \
-                  | jq --raw-output '.[] | select(.name == "VERSION") | .value' \
+          APP=$(\
+              docker buildx bake --list type=variables,format=json --progress=quiet -f docker-bake.hcl \
+                  | jq --raw-output '.[] | select(.name == "APP") | .value' \
           )
+          if [ -n "${{ inputs.version }}" ]; then
+            VERSION="${{ inputs.version }}"
+          else
+            VERSION="${{ github.ref_name }}"
+          fi
+          if [ -z "$VERSION"  ]; then
+            echo "version is missing, exiting..."
+            exit 1
+          fi
+          VERSION="${VERSION#v}"
 
           echo "platforms=${PLATFORMS}" >> $GITHUB_OUTPUT
           echo "source=${SOURCE}" >> $GITHUB_OUTPUT
+          echo "app=${APP}" >> $GITHUB_OUTPUT
           echo "version=${VERSION}" >> $GITHUB_OUTPUT
-
   build:
     needs: plan
     name: Build (${{ matrix.platform }})
-    runs-on: ubuntu-latest
+    runs-on: ${{ startsWith(matrix.platform, 'linux/arm') && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
     strategy: 
       fail-fast: false
       matrix: 
@@ -47,6 +72,13 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
 
+      - name: Get Target Architecture
+        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
+        id: target
+        with:
+          script: |
+            core.setOutput('arch', '${{ matrix.platform }}'.split('/').pop());
+    
       - name: Login to GitHub Container Registry
         uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
         with:
@@ -65,39 +97,32 @@ jobs:
         with:
           flavor: latest=false
           images: |
-            ghcr.io/${{ github.repository_owner }}/${{ inputs.app }}
+            ghcr.io/${{ github.repository_owner }}/${{ needs.plan.outputs.app }}
           tags: |
-            type=semver,pattern={{version}},value=${{ steps.app-versions.outputs.semantic }}
-            type=semver,pattern={{major}}.{{minor}},value=${{ steps.app-versions.outputs.semantic }},enable=${{ steps.app-versions.outputs.is-valid-semver }}
-            type=semver,pattern={{major}},value=${{ steps.app-versions.outputs.semantic }},enable=${{ steps.app-versions.outputs.is-valid-semver }}
-            type=raw,value=${{ steps.app-versions.outputs.raw }},enable=${{ steps.app-versions.outputs.is-valid-semver }}
+            type=semver,pattern={{version}},vault=${{ needs.plan.outputs.version }}
+            type=semver,pattern={{major}}.{{minor}},vault=${{ needs.plan.outputs.version }}
+            type=semver,pattern={{major}},vault=${{ needs.plan.outputs.version }}
             type=raw,value=rolling
 
-            type=semver,pattern={{version}}
-            type=semver,pattern={{major}}.{{minor}}
-            type=raw,value=latest,event=branch,enable={{is_default_branch}}
-          flavor: |
-            latest=auto
-
-      # Build and push Docker image with Buildx (don't push on PR)
-      # https://github.com/docker/build-push-action
-      - name: Build and push Docker image
-        id: build-and-push
-        uses: docker/build-push-action@v5 # v5.0.0
+      - name: Build Application
+        uses: docker/bake-action@37816e747588cb137173af99ab33873600c46ea8 # v6.8.0
+        id: bake
         with:
-          provenance: false
-          context: ./config_v5
-          platforms: linux/amd64,linux/arm64
-          push: ${{ github.event_name != 'pull_request' }}
-          tags: ${{ steps.meta.outputs.tags }}
-          labels: ${{ steps.meta.outputs.labels }}
-          annotations: ${{ steps.meta.outputs.annotations }}
-          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache
-          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache,mode=max
-
-      - name: Docker Hub Description
-        uses: peter-evans/dockerhub-description@v4
-        with:
-          username: ${{ github.actor }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
-          repository: ${{ env.IMAGE_NAME }}
+          files: |
+            ./docker-bake.hcl
+            cwd://${{ steps.meta.outputs.bake-file }}
+          set: |
+            *.args.VENDOR=${{ github.repository_owner }}
+            *.cache-from=${{ format('type=registry,ref=ghcr.io/{0}/build_cache:{1}-{2},mode=max', github.repository_owner, needs.plan.outputs.app, steps.target.outputs.arch) }}
+            *.cache-to=${{ inputs.release && format('type=registry,ref=ghcr.io/{0}/build_cache:{1}-{2},mode=max,compression=zstd,force-compression=true', github.repository_owner, needs.plan.outputs.app, steps.target.outputs.arch) || '' }}
+            *.labels.org.opencontainers.image.title=${{ needs.plan.outputs.app }}
+            *.labels.org.opencontainers.image.url=https://ghcr.io/${{ github.repository_owner }}/${{ needs.plan.outputs.app }}
+            *.labels.org.opencontainers.image.version=${{ needs.plan.outputs.version }}
+            *.labels.org.opencontainers.image.revision=${{ github.sha }}
+            *.labels.org.opencontainers.image.vendor=${{ github.repository_owner }}
+            ${{ inputs.release && format('*.output=type=image,name=ghcr.io/{0}/{1},push-by-digest=true,name-canonical=true,push=true', github.repository_owner, needs.plan.outputs.app) || '*.output=type=docker' }}
+            *.platform=${{ matrix.platform }}
+            *.tags=
+          source: .
+          targets: image
+          workdir: .
